
package com.he.maven.module.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceImpl", targetNamespace = "http://service.jaxws.module.maven.he.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.he.maven.module.jaxws.client.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://service.jaxws.module.maven.he.com/", className = "com.he.maven.module.jaxws.client.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://service.jaxws.module.maven.he.com/", className = "com.he.maven.module.jaxws.client.GetPersonResponse")
    @Action(input = "http://service.jaxws.module.maven.he.com/ServiceImpl/getPersonRequest", output = "http://service.jaxws.module.maven.he.com/ServiceImpl/getPersonResponse")
    public Person getPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
